### ISSUE TITLE
Missing MVP: Add template for data (Assignment #2)

### ISSUE THREAD

**Issue by elaewin** [justdisa/portfolio#8]
As a developer, I want portfolio items displayed with a repeatable template, so that I can reuse it, and abstract out the details for individual projects.

Technical Requirements:
* Think of some ideas for your source data, and code it up in its own file! Build out an array of three objects to start with, all having similar properties.
* Use jQuery to clone the example markup for each project, as you add additional content.
* Your "Project" prototype should have a .toHtml() function that adds new data to the DOM.

**Comment by justdisa** [comment]
Fixed.
